SEEED_BME680_Project: bme680.c File Reference
bme680.c File Reference
Sensor driver for BME680 sensor.
#include "bme680.h"
Functions
static int8_t get_calib_data (struct bme680_dev *dev)
This internal API is used to read the calibrated data from the sensor.
static int8_t set_gas_config (struct bme680_dev *dev)
This internal API is used to set the gas configuration of the sensor.
static int8_t get_gas_config (struct bme680_dev *dev)
This internal API is used to get the gas configuration of the sensor.
static uint8_t calc_heater_dur (uint16_t dur)
This internal API is used to calculate the Heat duration value.
static int16_t calc_temperature (uint32_t temp_adc, struct bme680_dev *dev)
This internal API is used to calculate the temperature value.
static uint32_t calc_pressure (uint32_t pres_adc, const struct bme680_dev *dev)
This internal API is used to calculate the pressure value.
static uint32_t calc_humidity (uint16_t hum_adc, const struct bme680_dev *dev)
This internal API is used to calculate the humidity value.
static uint32_t calc_gas_resistance (uint16_t gas_res_adc, uint8_t gas_range, const struct bme680_dev *dev)
This internal API is used to calculate the Gas Resistance value.
static uint8_t calc_heater_res (uint16_t temp, const struct bme680_dev *dev)
This internal API is used to calculate the Heat Resistance value.
static int8_t read_field_data (struct bme680_field_data *data, struct bme680_dev *dev)
This internal API is used to calculate the field data of sensor.
static int8_t set_mem_page (uint8_t reg_addr, struct bme680_dev *dev)
This internal API is used to set the memory page based on register address.
static int8_t get_mem_page (struct bme680_dev *dev)
This internal API is used to get the memory page based on register address.
static int8_t null_ptr_check (const struct bme680_dev *dev)
This internal API is used to validate the device pointer for null conditions.
static int8_t boundary_check (uint8_t *value, uint8_t min, uint8_t max, struct bme680_dev *dev)
This internal API is used to check the boundary conditions.
int8_t bme680_init (struct bme680_dev *dev)
This API is the entry point. It reads the chip-id and calibration data from the sensor.
int8_t bme680_get_regs (uint8_t reg_addr, uint8_t *reg_data, uint16_t len, struct bme680_dev *dev)
This API reads the data from the given register address of the sensor.
int8_t bme680_set_regs (const uint8_t *reg_addr, const uint8_t *reg_data, uint8_t len, struct bme680_dev *dev)
This API writes the given data to the register address of the sensor.
int8_t bme680_soft_reset (struct bme680_dev *dev)
This API performs the soft reset of the sensor.
int8_t bme680_set_sensor_settings (uint16_t desired_settings, struct bme680_dev *dev)
This API is used to set the oversampling, filter and T,P,H, gas selection settings in the sensor.
int8_t bme680_get_sensor_settings (uint16_t desired_settings, struct bme680_dev *dev)
This API is used to get the oversampling, filter and T,P,H, gas selection settings in the sensor.
int8_t bme680_set_sensor_mode (struct bme680_dev *dev)
This API is used to set the power mode of the sensor.
int8_t bme680_get_sensor_mode (struct bme680_dev *dev)
This API is used to get the power mode of the sensor.
void bme680_set_profile_dur (uint16_t duration, struct bme680_dev *dev)
This API is used to set the profile duration of the sensor.
void bme680_get_profile_dur (uint16_t *duration, const struct bme680_dev *dev)
This API is used to get the profile duration of the sensor.
int8_t bme680_get_sensor_data (struct bme680_field_data *data, struct bme680_dev *dev)
This API reads the pressure, temperature and humidity and gas data from the sensor, compensates the data and store it in the bme680_data structure instance passed by the user.
Variables
uint32_t lookupTable1 [16]
uint32_t lookupTable2 [16]
Detailed Description
Sensor driver for BME680 sensor.
Definition in file bme680.c.
Function Documentation
static int8_t boundary_check (uint8_t * value, uint8_t min, uint8_t max, struct bme680_dev * dev) static
This internal API is used to check the boundary conditions.
This internal API is used to validate the boundary conditions.
Parameters
[in] value :pointer to the value.
[in] min :minimum value.
[in] max :maximum value.
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 1111 of file bme680.c.
References BME680_E_NULL_PTR, BME680_I_MAX_CORRECTION, BME680_I_MIN_CORRECTION, BME680_OK, bme680_dev::info_msg, and NULL.
Referenced by bme680_set_sensor_settings().
static uint32_t calc_gas_resistance (uint16_t gas_res_adc, uint8_t gas_range, const struct bme680_dev * dev) static
This internal API is used to calculate the Gas Resistance value.
Parameters
[in] dev :Structure instance of bme680_dev.
[in] gas_res_adc :Contains the Gas Resistance ADC value.
[in] gas_range :Contains the range of gas values.
Returns
uint32_t calculated gas resistance.
Definition at line 925 of file bme680.c.
References bme680_dev::calib, lookupTable1, lookupTable2, and bme680_calib_data::range_sw_err.
Referenced by read_field_data().
static uint8_t calc_heater_dur (uint16_t dur) static
This internal API is used to calculate the Heat duration value.
Parameters
[in] dur :Value of the duration to be shared.
Returns
uint8_t threshold duration after calculation.
Definition at line 973 of file bme680.c.
Referenced by set_gas_config().
static uint8_t calc_heater_res (uint16_t temp, const struct bme680_dev * dev) static
This internal API is used to calculate the Heat Resistance value.
Parameters
[in] dev :Structure instance of bme680_dev.
[in] temp :Contains the temporary value.
Returns
uint8_t calculated heater resistance.
Definition at line 944 of file bme680.c.
References bme680_dev::amb_temp, bme680_dev::calib, bme680_calib_data::par_gh1, bme680_calib_data::par_gh2, bme680_calib_data::par_gh3, bme680_calib_data::res_heat_range, and bme680_calib_data::res_heat_val.
Referenced by set_gas_config().
static uint32_t calc_humidity (uint16_t hum_adc, const struct bme680_dev * dev) static
This internal API is used to calculate the humidity value.
Parameters
[in] dev :Structure instance of bme680_dev.
[in] hum_adc :Contains the humidity ADC value.
Returns
uint32_t calculated humidity.
Definition at line 889 of file bme680.c.
References bme680_dev::calib, bme680_calib_data::par_h1, bme680_calib_data::par_h2, bme680_calib_data::par_h3, bme680_calib_data::par_h4, bme680_calib_data::par_h5, bme680_calib_data::par_h6, bme680_calib_data::par_h7, and bme680_calib_data::t_fine.
Referenced by read_field_data().
static uint32_t calc_pressure (uint32_t pres_adc, const struct bme680_dev * dev) static
This internal API is used to calculate the pressure value.
Parameters
[in] dev :Structure instance of bme680_dev.
[in] pres_adc :Contains the pressure ADC value .
Returns
uint32_t calculated pressure.
Definition at line 846 of file bme680.c.
References bme680_dev::calib, bme680_calib_data::par_p1, bme680_calib_data::par_p10, bme680_calib_data::par_p2, bme680_calib_data::par_p3, bme680_calib_data::par_p4, bme680_calib_data::par_p5, bme680_calib_data::par_p6, bme680_calib_data::par_p7, bme680_calib_data::par_p8, bme680_calib_data::par_p9, and bme680_calib_data::t_fine.
Referenced by read_field_data().
static int16_t calc_temperature (uint32_t temp_adc, struct bme680_dev * dev) static
This internal API is used to calculate the temperature value.
Parameters
[in] dev :Structure instance of bme680_dev.
[in] temp_adc :Contains the temperature ADC value .
Returns
uint32_t calculated temperature.
Definition at line 826 of file bme680.c.
References bme680_dev::calib, bme680_calib_data::par_t1, bme680_calib_data::par_t2, bme680_calib_data::par_t3, and bme680_calib_data::t_fine.
Referenced by read_field_data().
static int8_t get_calib_data (struct bme680_dev * dev) static
This internal API is used to read the calibrated data from the sensor.
This function is used to retrieve the calibration data from the image registers of the sensor.
Note
Registers 89h to A1h for calibration data 1 to 24 from bit 0 to 7
Registers E1h to F0h for calibration data 25 to 40 from bit 0 to 7
Parameters
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status.
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 679 of file bme680.c.
References BME680_ADDR_RANGE_SW_ERR_ADDR, BME680_ADDR_RES_HEAT_RANGE_ADDR, BME680_ADDR_RES_HEAT_VAL_ADDR, BME680_BIT_H1_DATA_MSK, BME680_COEFF_ADDR1, BME680_COEFF_ADDR1_LEN, BME680_COEFF_ADDR2, BME680_COEFF_ADDR2_LEN, BME680_COEFF_SIZE, BME680_CONCAT_BYTES, bme680_get_regs(), BME680_GH1_REG, BME680_GH2_LSB_REG, BME680_GH2_MSB_REG, BME680_GH3_REG, BME680_H1_LSB_REG, BME680_H1_MSB_REG, BME680_H2_LSB_REG, BME680_H2_MSB_REG, BME680_H3_REG, BME680_H4_REG, BME680_H5_REG, BME680_H6_REG, BME680_H7_REG, BME680_HUM_REG_SHIFT_VAL, BME680_OK, BME680_P10_REG, BME680_P1_LSB_REG, BME680_P1_MSB_REG, BME680_P2_LSB_REG, BME680_P2_MSB_REG, BME680_P3_REG, BME680_P4_LSB_REG, BME680_P4_MSB_REG, BME680_P5_LSB_REG, BME680_P5_MSB_REG, BME680_P6_REG, BME680_P7_REG, BME680_P8_LSB_REG, BME680_P8_MSB_REG, BME680_P9_LSB_REG, BME680_P9_MSB_REG, BME680_RHRANGE_MSK, BME680_RSERROR_MSK, BME680_T1_LSB_REG, BME680_T1_MSB_REG, BME680_T2_LSB_REG, BME680_T2_MSB_REG, BME680_T3_REG, bme680_dev::calib, null_ptr_check(), bme680_calib_data::par_gh1, bme680_calib_data::par_gh2, bme680_calib_data::par_gh3, bme680_calib_data::par_h1, bme680_calib_data::par_h2, bme680_calib_data::par_h3, bme680_calib_data::par_h4, bme680_calib_data::par_h5, bme680_calib_data::par_h6, bme680_calib_data::par_h7, bme680_calib_data::par_p1, bme680_calib_data::par_p10, bme680_calib_data::par_p2, bme680_calib_data::par_p3, bme680_calib_data::par_p4, bme680_calib_data::par_p5, bme680_calib_data::par_p6, bme680_calib_data::par_p7, bme680_calib_data::par_p8, bme680_calib_data::par_p9, bme680_calib_data::par_t1, bme680_calib_data::par_t2, bme680_calib_data::par_t3, bme680_calib_data::range_sw_err, bme680_calib_data::res_heat_range, and bme680_calib_data::res_heat_val.
Referenced by bme680_init().
static int8_t get_gas_config (struct bme680_dev * dev) static
This internal API is used to get the gas configuration of the sensor.
Parameters
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status.
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 788 of file bme680.c.
References BME680_ADDR_GAS_CONF_START, BME680_ADDR_SENS_CONF_START, BME680_GAS_HEATER_PROF_LEN_MAX, bme680_get_regs(), BME680_OK, BME680_SPI_INTF, bme680_dev::gas_sett, bme680_gas_sett::heatr_dur, bme680_gas_sett::heatr_temp, bme680_dev::intf, null_ptr_check(), and set_mem_page().
Referenced by bme680_get_sensor_settings().
static int8_t get_mem_page (struct bme680_dev * dev) static
This internal API is used to get the memory page based on register address.
The value of memory page
value Description
0 BME680_PAGE0_SPI
1 BME680_PAGE1_SPI
Parameters
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 1089 of file bme680.c.
References BME680_E_COM_FAIL, BME680_MEM_PAGE_ADDR, BME680_MEM_PAGE_MSK, BME680_OK, BME680_SPI_RD_MSK, bme680_dev::com_rslt, bme680_dev::dev_id, bme680_dev::mem_page, null_ptr_check(), and bme680_dev::read.
Referenced by bme680_soft_reset().
static int8_t null_ptr_check (const struct bme680_dev * dev) static
This internal API is used to validate the device pointer for null conditions.
This internal API is used to validate the device structure pointer for null conditions.
Parameters
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 1139 of file bme680.c.
References BME680_E_NULL_PTR, BME680_OK, bme680_dev::delay_ms, NULL, bme680_dev::read, and bme680_dev::write.
Referenced by bme680_get_regs(), bme680_get_sensor_data(), bme680_get_sensor_mode(), bme680_get_sensor_settings(), bme680_init(), bme680_set_regs(), bme680_set_sensor_mode(), bme680_set_sensor_settings(), bme680_soft_reset(), get_calib_data(), get_gas_config(), get_mem_page(), read_field_data(), set_gas_config(), and set_mem_page().
static int8_t read_field_data (struct bme680_field_data * data, struct bme680_dev * dev) static
This internal API is used to calculate the field data of sensor.
Parameters
[out] data :Structure instance to hold the data
[in] dev :Structure instance of bme680_dev.
Returns
int8_t result of the field data from sensor.
Definition at line 994 of file bme680.c.
References BME680_FIELD0_ADDR, BME680_FIELD_LENGTH, BME680_GAS_INDEX_MSK, BME680_GAS_RANGE_MSK, BME680_GASM_VALID_MSK, bme680_get_regs(), BME680_HEAT_STAB_MSK, BME680_NEW_DATA_MSK, BME680_OK, BME680_POLL_PERIOD_MS, BME680_W_NO_NEW_DATA, calc_gas_resistance(), calc_humidity(), calc_pressure(), calc_temperature(), bme680_dev::delay_ms, bme680_field_data::gas_index, bme680_field_data::gas_resistance, bme680_field_data::humidity, bme680_field_data::meas_index, null_ptr_check(), bme680_field_data::pressure, bme680_field_data::status, and bme680_field_data::temperature.
Referenced by bme680_get_sensor_data().
static int8_t set_gas_config (struct bme680_dev * dev) static
This internal API is used to set the gas configuration of the sensor.
Parameters
[in] dev :Structure instance of bme680_dev.
Returns
Result of API execution status.
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 758 of file bme680.c.
References BME680_FORCED_MODE, BME680_GAS_WAIT0_ADDR, BME680_OK, BME680_RES_HEAT0_ADDR, bme680_set_regs(), BME680_W_DEFINE_PWR_MODE, calc_heater_dur(), calc_heater_res(), bme680_dev::gas_sett, bme680_gas_sett::heatr_dur, bme680_gas_sett::heatr_temp, bme680_gas_sett::nb_conv, null_ptr_check(), and bme680_dev::power_mode.
Referenced by bme680_set_sensor_settings().
static int8_t set_mem_page (uint8_t reg_addr, struct bme680_dev * dev) static
This internal API is used to set the memory page based on register address.
The value of memory page
value Description
0 BME680_PAGE0_SPI
1 BME680_PAGE1_SPI
Parameters
[in] dev :Structure instance of bme680_dev.
[in] reg_addr :Contains the register address array.
Returns
Result of API execution status
Return values
zero -> Success / +ve value -> Warning / -ve value -> Error
Definition at line 1050 of file bme680.c.
References BME680_E_COM_FAIL, BME680_MEM_PAGE0, BME680_MEM_PAGE1, BME680_MEM_PAGE_ADDR, BME680_MEM_PAGE_MSK, BME680_OK, BME680_SPI_RD_MSK, BME680_SPI_WR_MSK, bme680_dev::com_rslt, bme680_dev::dev_id, bme680_dev::mem_page, null_ptr_check(), bme680_dev::read, and bme680_dev::write.
Referenced by bme680_get_regs(), bme680_set_regs(), and get_gas_config().
Variable Documentation
uint32_t lookupTable1[16]
Initial value:
= { UINT32_C(2147483647), UINT32_C(2147483647), UINT32_C(2147483647), UINT32_C(2147483647),
    UINT32_C(2147483647), UINT32_C(2126008810), UINT32_C(2147483647), UINT32_C(2130303777), UINT32_C(2147483647),
    UINT32_C(2147483647), UINT32_C(2143188679), UINT32_C(2136746228), UINT32_C(2147483647), UINT32_C(2126008810),
    UINT32_C(2147483647), UINT32_C(2147483647) }
static variables Look up table for the possible gas range values
Definition at line 54 of file bme680.c.
Referenced by calc_gas_resistance().
uint32_t lookupTable2[16]
Initial value:
= { UINT32_C(4096000000), UINT32_C(2048000000), UINT32_C(1024000000), UINT32_C(512000000),
    UINT32_C(255744255), UINT32_C(127110228), UINT32_C(64000000), UINT32_C(32258064), UINT32_C(16016016), UINT32_C(
        8000000), UINT32_C(4000000), UINT32_C(2000000), UINT32_C(1000000), UINT32_C(500000), UINT32_C(250000),
    UINT32_C(125000) }
Look up table for the possible gas range values
Definition at line 59 of file bme680.c.
Referenced by calc_gas_resistance().