SEEED_BME680_Project: Seeed_BME680 Class Reference
Seeed_BME680 Class Reference
#include <seeed_bme680.h>
Public Member Functions
Seeed_BME680 (uint8_t iic_addr)
constructor of IIC interface.
Seeed_BME680 (int8_t cs=10, int8_t mosi=11, int8_t miso=12, int8_t sck=13)
constructor of SPI interface.
bool init ()
Initialization of sensor.
int8_t read_sensor_data (void)
Getting four kinds of result value from the sensor.
float read_temperature (void)
This function implements the temperature value of the read sensor.
float read_pressure (void)
This function implements the pressure value of the read sensor.
float read_humidity (void)
This function implements the humidity value of the read sensor.
float read_gas (void)
This function implements the gas value of the read sensor.
Public Attributes
sensor_result_t sensor_result_value
Private Attributes
struct bme680_dev sensor_param
Detailed Description
main class
Definition at line 49 of file seeed_bme680.h.
Constructor & Destructor Documentation
Seeed_BME680::Seeed_BME680 (uint8_t addr)
constructor of IIC interface.
Parameters
addr The BME680 device IIC address.
Returns
NONE.
Definition at line 34 of file seeed_bme680.cpp.
References BME680_I2C_INTF, bme680_dev::dev_id, bme680_dev::intf, and sensor_param.
Seeed_BME680::Seeed_BME680 (int8_t cs = 10, int8_t mosi = 11, int8_t miso = 12, int8_t sck = 13)
constructor of SPI interface.
Parameters
cs The cs pin of SPI interface,Default value is 10;
mosi The mosi pin of SPI interface,Default value is 11;
miso The miso pin of SPI interface,Default value is 12;
sck The sck pin of SPI interface,Default value is 13;
Note
It will call the different SPI transmission API when user customizes SPI pin
Returns
NONE.
Definition at line 50 of file seeed_bme680.cpp.
References BME680_SPI_INTF, bme680_dev::intf, sensor_param, spi_pinmap_cs, spi_pinmap_miso, spi_pinmap_mosi, spi_pinmap_sck, and user_define_spi_pinmap_flag.
Member Function Documentation
bool Seeed_BME680::init ()
Initialization of sensor.
Returns
ture or false
Definition at line 353 of file seeed_bme680.cpp.
References BME680_I2C_INTF, bme680_init(), BME680_OK, BME680_SPI_INTF, bme680_dev::calib, bme680_dev::delay_ms, delay_msec(), bme680_dev::dev_id, iic_read(), iic_write(), bme680_dev::intf, bme680_calib_data::par_gh1, bme680_calib_data::par_gh2, bme680_calib_data::par_gh3, bme680_calib_data::par_h1, bme680_calib_data::par_h2, bme680_calib_data::par_h3, bme680_calib_data::par_h4, bme680_calib_data::par_h5, bme680_calib_data::par_h6, bme680_calib_data::par_h7, bme680_calib_data::par_p1, bme680_calib_data::par_p10, bme680_calib_data::par_p2, bme680_calib_data::par_p3, bme680_calib_data::par_p4, bme680_calib_data::par_p5, bme680_calib_data::par_p6, bme680_calib_data::par_p7, bme680_calib_data::par_p8, bme680_calib_data::par_p9, bme680_calib_data::par_t1, bme680_calib_data::par_t2, bme680_calib_data::par_t3, bme680_calib_data::range_sw_err, bme680_dev::read, bme680_calib_data::res_heat_range, bme680_calib_data::res_heat_val, sensor_param, spi_pinmap_cs, spi_pinmap_miso, spi_pinmap_mosi, spi_pinmap_sck, spi_read(), spi_write(), user_define_spi_pinmap_flag, and bme680_dev::write.
float Seeed_BME680::read_gas (void)
This function implements the gas value of the read sensor.
Returns
sensor_result_value.gas The result of gas value.
Definition at line 113 of file seeed_bme680.cpp.
References sensor_result_t::gas, read_sensor_data(), and sensor_result_value.
float Seeed_BME680::read_humidity (void)
This function implements the humidity value of the read sensor.
Returns
sensor_result_value.humidity The result of humidity value.
Definition at line 100 of file seeed_bme680.cpp.
References sensor_result_t::humidity, read_sensor_data(), and sensor_result_value.
float Seeed_BME680::read_pressure (void)
This function implements the pressure value of the read sensor.
Returns
sensor_result_value.pressure The result of pressure value.
Definition at line 87 of file seeed_bme680.cpp.
References sensor_result_t::pressure, read_sensor_data(), and sensor_result_value.
int8_t Seeed_BME680::read_sensor_data (void)
Getting four kinds of result value from the sensor.
Returns
Result of function excution. The normal exit is only when it returns BME680_OK(0).
<It is necessary to delay for a duration time
Definition at line 126 of file seeed_bme680.cpp.
References BME680_ENABLE_GAS_MEAS, BME680_FILTER_SEL, BME680_FORCED_MODE, BME680_GAS_SENSOR_SEL, bme680_get_profile_dur(), bme680_get_sensor_data(), BME680_HEAT_STAB_MSK, BME680_OK, BME680_OS_16X, BME680_OS_1X, BME680_OS_2X, BME680_OSH_SEL, BME680_OSP_SEL, BME680_OST_SEL, bme680_set_sensor_mode(), bme680_set_sensor_settings(), sensor_result_t::gas, bme680_field_data::gas_resistance, bme680_dev::gas_sett, bme680_gas_sett::heatr_dur, bme680_gas_sett::heatr_temp, sensor_result_t::humidity, bme680_field_data::humidity, bme680_tph_sett::os_hum, bme680_tph_sett::os_pres, bme680_tph_sett::os_temp, bme680_dev::power_mode, sensor_result_t::pressure, bme680_field_data::pressure, bme680_gas_sett::run_gas, sensor_param, sensor_result_value, bme680_field_data::status, sensor_result_t::temperature, bme680_field_data::temperature, and bme680_dev::tph_sett.
Referenced by read_gas(), read_humidity(), read_pressure(), and read_temperature().
float Seeed_BME680::read_temperature (void)
This function implements the temperature value of the read sensor.
Returns
sensor_result_value.temperature The result of temperature value.
Definition at line 74 of file seeed_bme680.cpp.
References read_sensor_data(), sensor_result_value, and sensor_result_t::temperature.
Member Data Documentation
struct bme680_dev Seeed_BME680::sensor_param private
Official LIB structure.
Definition at line 66 of file seeed_bme680.h.
Referenced by init(), read_sensor_data(), and Seeed_BME680().
sensor_result_t Seeed_BME680::sensor_result_value
Definition at line 62 of file seeed_bme680.h.
Referenced by read_gas(), read_humidity(), read_pressure(), read_sensor_data(), and read_temperature().
The documentation for this class was generated from the following files:
seeed_bme680.h
seeed_bme680.cpp