SEEED_BME680_Project: seeed_bme680.cpp File Reference
seeed_bme680.cpp File Reference
#include "seeed_bme680.h"
Functions
int8_t iic_read (uint8_t dev_id, uint8_t reg_addr, uint8_t *reg_data, uint16_t len)
IIC reading interface.
int8_t iic_write (uint8_t dev_id, uint8_t reg_addr, uint8_t *reg_data, uint16_t len)
IIC wrting interface.
static uint8_t spi_transfer (uint8_t x)
SPI read and write one byte.
static int8_t spi_read (uint8_t cspin, uint8_t reg_addr, uint8_t *reg_data, uint16_t len)
SPI reading interface.
static int8_t spi_write (uint8_t cspin, uint8_t reg_addr, uint8_t *reg_data, uint16_t len)
SPI wrting interface.
static void delay_msec (uint32_t ms)
delay milliseconds
Variables
static int8_t spi_pinmap_cs
The main driver file of BME680 sensor.
static int8_t spi_pinmap_mosi
static int8_t spi_pinmap_miso
static int8_t spi_pinmap_sck
static int8_t user_define_spi_pinmap_flag
Detailed Description
Library for BME680
Copyright (c) 2013 Seeed Technology Co., Ltd.
Author
: downey
Date
Create Time : 2017/12/08 Change Log :
Definition in file seeed_bme680.cpp.
Function Documentation
static void delay_msec (uint32_t ms) static
delay milliseconds
Parameters
ms milliseconds
Returns
NONE
Definition at line 344 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init().
int8_t iic_read (uint8_t dev_id, uint8_t reg_addr, uint8_t * reg_data, uint16_t len)
IIC reading interface.
Parameters
dev_id IIC device address
reg_addr The register address for operated.
reg_data Storing data read from registers.
len Length of data.
Returns
The normal exit is only when it returns 0.
Definition at line 202 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init().
int8_t iic_write (uint8_t dev_id, uint8_t reg_addr, uint8_t * reg_data, uint16_t len)
IIC wrting interface.
Parameters
dev_id IIC device address
reg_addr The register address for operated.
reg_data The data need to be transmitted.
len Length of data.
Returns
The normal exit is only when it returns 0.
Definition at line 227 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init().
static int8_t spi_read (uint8_t cspin, uint8_t reg_addr, uint8_t * reg_data, uint16_t len) static
SPI reading interface.
Parameters
cspin cspin of SPI hardware interface.
reg_addr The register address for operated.
reg_data Storing data read from registers.
len Length of data.
Returns
The normal exit is only when it returns 0.
Definition at line 278 of file seeed_bme680.cpp.
References BME680_DEFAULT_SPIFREQ, spi_transfer(), and user_define_spi_pinmap_flag.
Referenced by Seeed_BME680::init().
static uint8_t spi_transfer (uint8_t x) static
SPI read and write one byte.
Parameters
x The byte needs to be transmitted.
Returns
The byte received from sensor.
Definition at line 247 of file seeed_bme680.cpp.
References spi_pinmap_miso, spi_pinmap_mosi, spi_pinmap_sck, and user_define_spi_pinmap_flag.
Referenced by spi_read(), and spi_write().
static int8_t spi_write (uint8_t cspin, uint8_t reg_addr, uint8_t * reg_data, uint16_t len) static
SPI wrting interface.
Parameters
cspin cspin of SPI hardware interface.
reg_addr The register address for operated.
reg_data The data need to be transmitted.
len Length of data.
Returns
The normal exit is only when it returns 0.
Definition at line 312 of file seeed_bme680.cpp.
References BME680_DEFAULT_SPIFREQ, spi_transfer(), and user_define_spi_pinmap_flag.
Referenced by Seeed_BME680::init().
Variable Documentation
int8_t spi_pinmap_cs static
The main driver file of BME680 sensor.
BME680 support for temperature,humidity,indoor-air_quality(gas) and pressure value measurement, The result of measurement is stored in class Seeed_BME680->sensor_result_value. BME680 support for two communication protocol-SPI and IIC,The different communication protocol corresponding different constructor.Furthermore,you can customize the pin when your development board's SPI interface is mismatch with official.All you have to do is choose different ways to instantiate object.
Definition at line 23 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init(), and Seeed_BME680::Seeed_BME680().
int8_t spi_pinmap_miso static
Definition at line 25 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init(), Seeed_BME680::Seeed_BME680(), and spi_transfer().
int8_t spi_pinmap_mosi static
Definition at line 24 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init(), Seeed_BME680::Seeed_BME680(), and spi_transfer().
int8_t spi_pinmap_sck static
Definition at line 26 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init(), Seeed_BME680::Seeed_BME680(), and spi_transfer().
int8_t user_define_spi_pinmap_flag static
Definition at line 27 of file seeed_bme680.cpp.
Referenced by Seeed_BME680::init(), Seeed_BME680::Seeed_BME680(), spi_read(), spi_transfer(), and spi_write().